# frozen_string_literal: true

require 'rake'
require_relative '../../lib/ruby/bunny_connection_factory'

require_relative 'db/connection'

desc 'Run Sporting Event Listener'
task :run_listener do
  require_relative 'write/sporting_event_listener'
  SportingEventListener.new.listen
end

desc 'Publish Sporting Event'
task :publish do
  require_relative 'write/sporting_event_publisher'
  SportingEventPublisher.new.send('write/data.csv')
end

desc 'Sporting Event Summary'
task :summary do
  Connection.connect
  require_relative 'models/sporting_event'
  puts ''"
  SportingEvent
  count #{SportingEvent.count}
  "''
end

desc 'Migrate DB'
task :db_migrate do
  Connection.connect
  require_relative 'db/migrate/migration_one'
end
