# frozen_string_literal: true

require 'rake'
require '../../libs/heart_core/lib/heart_core'

require_relative 'models/sporting_event'
require_relative 'lib/csv_reader'
require_relative 'config/about'
require_relative 'config/db'
require_relative 'config/default_message_attributes'

desc 'Clean Sporting Event'
task clean: 'db:connect' do
  Heart::Core::QueueManager.new.purge_all(%w[sporting_event_created sporting_event_created])
  SportingEvent.delete_all
  Heart::Core::OutboxMessage.delete_all
end

namespace :db do
  desc 'DB Connect'
  task :connect do
    require_relative 'config/db'
    Heart::Core::DbConnection.connect!
  end

  desc 'Migrate DB'
  task migrate: 'db:connect' do
    require_relative 'db/migrate/migration_one'
    require_relative 'db/migrate/db_outbox'
  end
end

desc 'Sporting Event Summary'
task summary: 'db:connect' do
  puts '' "
  Discovery Summary
  #{Heart::Core::Discovery::Registry.new.summary('app/')}
  " ''

  puts '' "
  SportingEvent
  count #{SportingEvent.count}

  Heart::Core::OutboxMessage
  sent count #{Heart::Core::OutboxMessage.where.not(sent_at: nil).count}
  unsent count #{Heart::Core::OutboxMessage.where(sent_at: nil).count}
  " ''
end

namespace :run do
  desc 'Run Sporting Event REST Server'
  task :server do
    ruby "#{__dir__}/api/rest_server.rb"
  end

  desc 'Run Create Sporting Event Listener'
  task create_listener: 'db:connect' do
    Heart::Core::EventListener.new('sporting_event_create').listen do |payload|
      sporting_events = Heart::Core::ActiveModelHelper.build_all(SportingEvent, JSON.parse(payload))
      sporting_events.map(&:save!)
    end
  end

  desc 'Run Sporting Event Created Listener'
  task created_listener: 'db:connect' do
    Heart::Core::EventListener.new('sporting_event_created').listen { |payload| puts payload }
  end

  desc 'Run Polling Publisher'
  task polling_publisher: 'db:connect' do
    Heart::Core::PollingPublisher.new.run
  end
end

desc 'Publish Single Sporting Event'
task :publish_all, [:publisher_class] => 'db:connect' do |t, args|
  args.with_defaults(publisher_class: 'Heart::Core::DirectPublisher')
  publisher_class = Object.const_get(args[:publisher_class])
  publisher_class.fetch_instance('sporting_event_create').publish { CsvReader.parse_csv('data.csv') }
end

desc 'Publish Single Sporting Event'
task :publish, [:internal_id] do |t, args|
  args.with_defaults(publisher_class: 'Heart::Core::DirectPublisher')
  internal_id = args[:internal_id]
  publisher_class = Object.const_get(args[:publisher_class])
  data = JSON.parse(CsvReader.parse_csv('data.csv')).select { |obj| obj['internal_id'] == internal_id }.to_json
  publisher_class.fetch_instance('sporting_event_create').publish { data }
end
