# frozen_string_literal: true

source 'https://rubygems.org'

gem 'activerecord'
gem 'bunny'
gem 'grape'
gem 'grape-swagger'
gem 'logging'
gem 'pg'
gem 'rack'
gem 'rake'
gem 'redis'
gem 'faraday'

gem 'pry'
gem 'rubocop'
gem 'rack-test'
