# frozen_string_literal: true

require_relative 'api'

desc 'Print out routes'
task :routes do
  SimpleCrud::API.routes.each do |route|
    info = route.instance_variable_get :@options
    description = '%-40s' % info[:description][0..39]
    method = '%-7s' % info[:method]
    puts "#{description}\t#{method}\t#{info[:prefix]}#{info[:namespace]}"
  end
end
