# frozen_string_literal: true

source 'https://rubygems.org'

gem 'activerecord'
gem 'bunny'
gem 'faraday'
gem 'grape'
gem 'grape-swagger'
gem 'logging'
gem 'pg'
gem 'rack'
gem 'rake'
gem 'redis'

group :test do
  gem 'pry'
  gem 'rack-test'
  gem 'rubocop'
  gem 'factory_bot'
  gem 'database_cleaner-active_record'
end